# Generated by Django 5.0.6 on 2024-06-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_dni', models.IntegerField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=100)),
                ('cli_apellido', models.CharField(max_length=100)),
                ('cli_telefono', models.CharField(max_length=9)),
                ('cli_direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('inm_codigo', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('inm_tipo', models.CharField(max_length=100)),
                ('inm_valor', models.FloatField()),
                ('inm_estado', models.CharField(max_length=100)),
                ('inm_des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('tra_dni', models.IntegerField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('tra_nombre', models.CharField(max_length=100)),
                ('tra_apellido', models.CharField(max_length=100)),
                ('tra_telefono', models.CharField(max_length=9)),
                ('tra_direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('cnt_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cnt_nombre', models.CharField(max_length=100)),
                ('cnt_formapago', models.CharField(max_length=20)),
                ('cnt_fechafirma', models.DateField()),
                ('cnt_fechacontrato', models.DateField()),
                ('cnt_estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cliente')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.inmueble')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.trabajador')),
            ],
        ),
    ]
