# Generated by Django 5.0.6 on 2024-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cnt_codigo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
